#my project

```{r, message=FALSE, warning=FALSE}


load.libraries <- c('tidyverse', 'gridExtra', 'dplyr', 'lubridate', 'ggplot2', 'stringr', 'randomForest', 'fastDummies', 'janitor', 'caret', 'AUC', 'plotrix')
install.lib <- load.libraries[!load.libraries %in% installed.packages()]
for(libs in install.lib) install.packages(libs, dependences = TRUE)
sapply(load.libraries, require, character = TRUE)

```
   
```{r, message=FALSE, warning=FALSE}

orders_data <- read.csv(file = "orders_data.csv") 

```


#make data anonymous 

```{r, message=FALSE, warning=FALSE}

Id <- unique(orders_data$buyer)

names(Id) <- c(1:length(Id))

Id_Conversion <- data.frame(buyer = Id, Person = names(Id))

orders_data <- merge(orders_data, Id_Conversion, by = "buyer") %>%
  subset(select = -buyer) %>%
  mutate("buyer" = as.character(Person)) %>%
  subset(select = -Person) 

```

```{r, message=FALSE, warning=FALSE}
dim(orders_data)



length(unique(orders_data$order_no))
```

  
```{r, message=FALSE, warning=FALSE}
colnames(orders_data)

#view a selection of the data
str(orders_data[1,c("sku", "ship_city", "item_total", "order_date", "description")])
```

```{r, message=FALSE, warning=FALSE}

#tidying all variables, and splitting order_date variable

orders_data <- orders_data %>% 
   mutate(ship_city = substr(ship_city, 1, nchar(ship_city)-1)) %>%
   mutate(shipping_fee   = as.double(gsub(",", "",(substr(shipping_fee, 4, nchar(shipping_fee)))))) %>% 
   mutate(item_total =   as.double(gsub(",", "",(substr(item_total, 4, nchar(item_total)))))) %>% 
   mutate(sku = substr(sku, 7,   nchar(sku))) %>% 
   mutate(day = substr(order_date, 1, 3)) %>%  
   mutate(order_time = substr(order_date, 19, nchar(order_date)-3)) %>%
   mutate(order_hour = hour(mdy_hm(paste("11/11/99", order_time, sep =" ")))) %>% 
   mutate(order_minute = minute(mdy_hm(paste("11/11/99", order_time, sep =" ")))) %>% 
   mutate(timezone = substr(order_date, nchar(order_date)-3, nchar(order_date))) %>% 
   mutate(order_date1 = substr(order_date, 6, 18)) %>% 
   mutate(order_date = dmy(substr(order_date, 6, 18))) %>% 
   mutate(ship_city = tolower(trimws(ship_city, which = "both"))) %>%
   mutate(ship_state = tolower(trimws(ship_state, which = "both"))) %>%
   mutate(description = tolower(trimws(description, which = "both"))) %>% 
   mutate(quantity = as.double((quantity)))



orders_data[is.na(orders_data$order_date), 'order_date'] <- 
  dmy(paste(substring(orders_data[is.na(orders_data$order_date), 'order_date1'], 1, 6), substring(orders_data[is.na(orders_data$order_date), 'order_date1'], 10, 13), sep=" "))

orders_data <- orders_data %>%
  subset(select = -c(order_date1, day, order_time))





#correcting one-off cities and states

orders_data[orders_data$ship_city == as.character("mumbai 400 026"), c("ship_city")] <- as.character("mumbai")

orders_data[orders_data$ship_city == as.character("navi mumbai"), c("ship_city")] <- as.character("mumbai")

orders_data[orders_data$ship_city == as.character("thane district"), c("ship_city")] <- as.character("thane")

orders_data[orders_data$ship_city == as.character("kodambakkam, chennai"), c("ship_city")] <- as.character("chennai")

orders_data[orders_data$ship_state == as.character("mohali,"), c("ship_state")] <- as.character("mohali")

orders_data[orders_data$ship_state == as.character("chandigarh,"), c("ship_state")] <- as.character("chandigarh")

#Feature engineering by tracking key words in description

orders_data <- orders_data %>%
  mutate(gender = 
           ifelse(str_detect(orders_data$description, 'women') | str_detect(orders_data$description, 'woman'), as.character('women'),
                  ifelse(str_detect(orders_data$description, ' men') | str_detect(orders_data$description, ' man')| str_detect(orders_data$description, ' gent'), as.character('men'),
                         ifelse(str_detect(orders_data$description, 'kid'), as.character('kid'), as.character('none')))))




#Tracking other key words in descriptions for more feature engineering
#assessories <- lipstick, jewelry box 
#bags <- bag, purse, 
#banks <- bank
#wallet <-wallet


orders_data <- orders_data %>%
  mutate(item_type = 
           ifelse(str_detect(orders_data$description, 'lipstick') | str_detect(orders_data$description, 'jewelry'), as.character('accessories'),
                  ifelse(str_detect(orders_data$description, 'bag') | str_detect(orders_data$description, 'purse'), as.character('bags'),
                         ifelse(str_detect(orders_data$description, 'bank'), as.character('banks'),
                                ifelse(str_detect(orders_data$description, 'wallet'), as.character('wallets'), as.character('none'))))))




#cleaing up one-off descriptions

orders_data$description[28] <- as.character('bright and colorful handmade shantiniketan leather ganesh ji piggy coin bank for kids/adults | home decor handicrafts (black)')

orders_data$description[80] <- as.character('bright and colorful handmade shantiniketan leather ganesh ji piggy coin bank for kids/adults | home decor handicrafts (yellow)')

orders_data$description[105] <- as.character('bright and colorful handmade shantiniketan leather ganesh ji piggy coin bank for kids/adults | home decor handicrafts (blue)')

orders_data$description[124] <-as.character('bright and colorful handmade shantiniketan leather ganesh ji piggy coin bank for kids/adults | home decor handicrafts (green)') 

orders_data$description[143] <-  as.character('bright and colorful handmade shantiniketan leather ganesh ji piggy coin bank for kids/adults | home decor handicrafts (black)')

#splitting description by deliminator into more variables

orders_data <- orders_data %>% 
  mutate(description.1 = 
           trimws(vapply(str_split(description, "\\|"), '[', 1, FUN.VALUE = character(1)), which="both")) %>% 
  mutate(description.2 = 
           trimws(vapply(str_split(description, "\\|"), '[', 2, FUN.VALUE = character(1)), which="both")) %>% 
  mutate(description.3 = 
           trimws(vapply(str_split(description, "\\|"), '[', 3, FUN.VALUE = character(1)), which="both")) %>% 
  mutate(description.4 = trimws(vapply(str_split(description, "\\|"), '[', 4, FUN.VALUE = character(1)), which="both"))



#revalue function
my_revalue <- function(x, ...){
  reval <- list(...)

  from <- names(reval)
  to <- unlist(reval)

  out <- eval(parse(text= paste0("{", paste0(paste0("x[x ==", "'", from,"'", "]", "<-", "'", to, "'"), collapse= ";"), ";x", "}")))

  return(out)
}

#feature engineering order months and time of day

orders_data <- orders_data %>%
  mutate(month = as.integer(month(order_date)))


#order month
orders_data$month <- my_revalue(orders_data$month, "1"= "01 - January", "2"="02 - February", "3"="03 - March", "4"="04 - April", "5"="05 - May", "6"="06 - June", "7"="07 - July", "8"="08 - August", "9"="09 - September", "10"="10 - October", "11"="11 - November", "12"="12 - December")


#order time of day
orders_data <- orders_data %>% 
  mutate(tod = ifelse(order_hour < 6, as.character('night'), ifelse(order_hour< 12, as.character('morning'), ifelse(order_hour < 18, as.character('afternoon'), as.character('evening') ))))


```


  
   
#see the results  
   
```{r, message=FALSE, warning=FALSE}

colnames(orders_data)

str(orders_data[1, c("sku", "ship_city", "item_total", "order_date", "description.1", "gender", "item_type")])
```
